# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.URLField(max_length=255)),
                ('hash', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
